name: Gemini Assistant
on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  assistant:
    if: contains(github.event.comment.body, '/add-fireworks')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Gemini CLI
        uses: google-github-actions/run-gemini-cli@v0.1.11
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          prompt: "Ajoute une amélioration simple au projet Fireworks."
          settings: |
            {"model":"gemini-2.5-pro",
             "instructions":"FR. Patch minimal. Exemple : ajouter un bouton Screenshot pour sauvegarder le canvas, ou un slider pour ajuster le nombre de particules. Toujours mettre à jour README si besoin. Jamais d'approbation.",
             "pull_request":{"create_pr":true,"branch_prefix":"feat/gemini-"}}
